apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: httpd:2.4
          ports:
            - containerPort: 80
          env:
            - name: ENVIRONMENT
              value: "base"
