apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/frontend

namePrefix: staging-
namespace: frontend-staging

commonLabels:
  environment: staging
  cluster: staging

replicas:
  - name: frontend
    count: 2

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: staging
    target:
      kind: Deployment
      name: frontend
