apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../base/database

namePrefix: prod-
namespace: database-production

replicas:
  - count: 1
    name: database

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: production
    target:
      kind: Deployment
      name: database
labels:
  - includeSelectors: true
    pairs:
      cluster: production
      environment: production
