apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base/database

namePrefix: prod-
namespace: database-production

commonLabels:
  environment: production
  cluster: production

replicas:
- name: database
  count: 1

patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: production
  target:
    kind: Deployment
    name: database
