apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../base/backend

namePrefix: prod-
namespace: backend-production

replicas:
  - count: 3
    name: backend

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: production
    target:
      kind: Deployment
      name: backend
labels:
  - includeSelectors: true
    pairs:
      cluster: production
      environment: production
