apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base/frontend

namePrefix: prod-
namespace: frontend-production

commonLabels:
  environment: production
  cluster: production

replicas:
- name: frontend
  count: 3

patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: production
  target:
    kind: Deployment
    name: frontend
